default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USER", "rails_user") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "password123") %>
  host: <%= ENV.fetch("MYSQL_HOST", "localhost") %>
  port: <%= ENV.fetch("MYSQL_PORT", "3306") %>

development:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DATABASE", "groudonbattle_development") %>

test:
  <<: *default
  database: groudonbattle_test

production:
  <<: *default
  database: groudonbattle_production
  username: <%= ENV.fetch("DATABASE_USERNAME", "rails_user") %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
